// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.0--rc1
// source: albelt/order_srv/const.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 支付类型
type PayType int32

const (
	PayType_PAY_TYPE_UNSPECIFIED PayType = 0
	PayType_PAY_TYPE_WECHAT      PayType = 1 //微信
	PayType_PAY_TYPE_ALIPAY      PayType = 2 //支付宝
)

// Enum value maps for PayType.
var (
	PayType_name = map[int32]string{
		0: "PAY_TYPE_UNSPECIFIED",
		1: "PAY_TYPE_WECHAT",
		2: "PAY_TYPE_ALIPAY",
	}
	PayType_value = map[string]int32{
		"PAY_TYPE_UNSPECIFIED": 0,
		"PAY_TYPE_WECHAT":      1,
		"PAY_TYPE_ALIPAY":      2,
	}
)

func (x PayType) Enum() *PayType {
	p := new(PayType)
	*p = x
	return p
}

func (x PayType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayType) Descriptor() protoreflect.EnumDescriptor {
	return file_albelt_order_srv_const_proto_enumTypes[0].Descriptor()
}

func (PayType) Type() protoreflect.EnumType {
	return &file_albelt_order_srv_const_proto_enumTypes[0]
}

func (x PayType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayType.Descriptor instead.
func (PayType) EnumDescriptor() ([]byte, []int) {
	return file_albelt_order_srv_const_proto_rawDescGZIP(), []int{0}
}

// 订单状态
type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED OrderStatus = 0
	OrderStatus_ORDER_STATUS_PAYING      OrderStatus = 1 //待支付
	OrderStatus_ORDER_STATUS_CLOSED      OrderStatus = 2 //超时关闭
	OrderStatus_ORDER_STATUS_SUCCESS     OrderStatus = 3 //交易成功
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_PAYING",
		2: "ORDER_STATUS_CLOSED",
		3: "ORDER_STATUS_SUCCESS",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED": 0,
		"ORDER_STATUS_PAYING":      1,
		"ORDER_STATUS_CLOSED":      2,
		"ORDER_STATUS_SUCCESS":     3,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_albelt_order_srv_const_proto_enumTypes[1].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_albelt_order_srv_const_proto_enumTypes[1]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_albelt_order_srv_const_proto_rawDescGZIP(), []int{1}
}

var File_albelt_order_srv_const_proto protoreflect.FileDescriptor

var file_albelt_order_srv_const_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x6c, 0x62, 0x65, 0x6c, 0x74, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x73,
	0x72, 0x76, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x4d,
	0x0a, 0x07, 0x50, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x14, 0x50, 0x41, 0x59,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x50, 0x41, 0x59, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x57, 0x45, 0x43, 0x48, 0x41, 0x54, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x50, 0x41, 0x59, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x41, 0x4c, 0x49, 0x50, 0x41, 0x59, 0x10, 0x02, 0x2a, 0x77, 0x0a,
	0x0b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x18,
	0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x4f, 0x52,
	0x44, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x50, 0x41, 0x59, 0x49, 0x4e,
	0x47, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x5f, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x44, 0x10, 0x02, 0x12, 0x18, 0x0a, 0x14,
	0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x53, 0x55, 0x43,
	0x43, 0x45, 0x53, 0x53, 0x10, 0x03, 0x42, 0x0b, 0x5a, 0x09, 0x67, 0x6f, 0x2f, 0x3b, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_albelt_order_srv_const_proto_rawDescOnce sync.Once
	file_albelt_order_srv_const_proto_rawDescData = file_albelt_order_srv_const_proto_rawDesc
)

func file_albelt_order_srv_const_proto_rawDescGZIP() []byte {
	file_albelt_order_srv_const_proto_rawDescOnce.Do(func() {
		file_albelt_order_srv_const_proto_rawDescData = protoimpl.X.CompressGZIP(file_albelt_order_srv_const_proto_rawDescData)
	})
	return file_albelt_order_srv_const_proto_rawDescData
}

var file_albelt_order_srv_const_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_albelt_order_srv_const_proto_goTypes = []interface{}{
	(PayType)(0),     // 0: PayType
	(OrderStatus)(0), // 1: OrderStatus
}
var file_albelt_order_srv_const_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_albelt_order_srv_const_proto_init() }
func file_albelt_order_srv_const_proto_init() {
	if File_albelt_order_srv_const_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_albelt_order_srv_const_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_albelt_order_srv_const_proto_goTypes,
		DependencyIndexes: file_albelt_order_srv_const_proto_depIdxs,
		EnumInfos:         file_albelt_order_srv_const_proto_enumTypes,
	}.Build()
	File_albelt_order_srv_const_proto = out.File
	file_albelt_order_srv_const_proto_rawDesc = nil
	file_albelt_order_srv_const_proto_goTypes = nil
	file_albelt_order_srv_const_proto_depIdxs = nil
}
