// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.0--rc1
// source: albelt/user_srv/const.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Gender int32

const (
	Gender_GENDER_UNSPECIFIED Gender = 0
	Gender_GENDER_MALE        Gender = 1
	Gender_GENDER_FELAME      Gender = 2
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "GENDER_UNSPECIFIED",
		1: "GENDER_MALE",
		2: "GENDER_FELAME",
	}
	Gender_value = map[string]int32{
		"GENDER_UNSPECIFIED": 0,
		"GENDER_MALE":        1,
		"GENDER_FELAME":      2,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_albelt_user_srv_const_proto_enumTypes[0].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_albelt_user_srv_const_proto_enumTypes[0]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_albelt_user_srv_const_proto_rawDescGZIP(), []int{0}
}

type UserRole int32

const (
	UserRole_USER_ROLE_UNSPECIFIED UserRole = 0
	// 普通用户
	UserRole_USER_ROLE_NORMAL UserRole = 1
	// 管理员
	UserRole_USER_ROLE_ADMIN UserRole = 2
)

// Enum value maps for UserRole.
var (
	UserRole_name = map[int32]string{
		0: "USER_ROLE_UNSPECIFIED",
		1: "USER_ROLE_NORMAL",
		2: "USER_ROLE_ADMIN",
	}
	UserRole_value = map[string]int32{
		"USER_ROLE_UNSPECIFIED": 0,
		"USER_ROLE_NORMAL":      1,
		"USER_ROLE_ADMIN":       2,
	}
)

func (x UserRole) Enum() *UserRole {
	p := new(UserRole)
	*p = x
	return p
}

func (x UserRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRole) Descriptor() protoreflect.EnumDescriptor {
	return file_albelt_user_srv_const_proto_enumTypes[1].Descriptor()
}

func (UserRole) Type() protoreflect.EnumType {
	return &file_albelt_user_srv_const_proto_enumTypes[1]
}

func (x UserRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRole.Descriptor instead.
func (UserRole) EnumDescriptor() ([]byte, []int) {
	return file_albelt_user_srv_const_proto_rawDescGZIP(), []int{1}
}

// 短信验证码类型
type SmsType int32

const (
	SmsType_SMS_TYPE_UNSPECIFIED SmsType = 0
	// 注册
	SmsType_SMS_TYPE_REGISTER SmsType = 1
	// 登录
	SmsType_SMS_TYPE_LOGIN SmsType = 2
)

// Enum value maps for SmsType.
var (
	SmsType_name = map[int32]string{
		0: "SMS_TYPE_UNSPECIFIED",
		1: "SMS_TYPE_REGISTER",
		2: "SMS_TYPE_LOGIN",
	}
	SmsType_value = map[string]int32{
		"SMS_TYPE_UNSPECIFIED": 0,
		"SMS_TYPE_REGISTER":    1,
		"SMS_TYPE_LOGIN":       2,
	}
)

func (x SmsType) Enum() *SmsType {
	p := new(SmsType)
	*p = x
	return p
}

func (x SmsType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SmsType) Descriptor() protoreflect.EnumDescriptor {
	return file_albelt_user_srv_const_proto_enumTypes[2].Descriptor()
}

func (SmsType) Type() protoreflect.EnumType {
	return &file_albelt_user_srv_const_proto_enumTypes[2]
}

func (x SmsType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SmsType.Descriptor instead.
func (SmsType) EnumDescriptor() ([]byte, []int) {
	return file_albelt_user_srv_const_proto_rawDescGZIP(), []int{2}
}

var File_albelt_user_srv_const_proto protoreflect.FileDescriptor

var file_albelt_user_srv_const_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x6c, 0x62, 0x65, 0x6c, 0x74, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x72,
	0x76, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x44, 0x0a,
	0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x12, 0x47, 0x45, 0x4e, 0x44, 0x45,
	0x52, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x0f, 0x0a, 0x0b, 0x47, 0x45, 0x4e, 0x44, 0x45, 0x52, 0x5f, 0x4d, 0x41, 0x4c, 0x45, 0x10, 0x01,
	0x12, 0x11, 0x0a, 0x0d, 0x47, 0x45, 0x4e, 0x44, 0x45, 0x52, 0x5f, 0x46, 0x45, 0x4c, 0x41, 0x4d,
	0x45, 0x10, 0x02, 0x2a, 0x50, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x12,
	0x19, 0x0a, 0x15, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x55, 0x53,
	0x45, 0x52, 0x5f, 0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x4e, 0x4f, 0x52, 0x4d, 0x41, 0x4c, 0x10, 0x01,
	0x12, 0x13, 0x0a, 0x0f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x41, 0x44,
	0x4d, 0x49, 0x4e, 0x10, 0x02, 0x2a, 0x4e, 0x0a, 0x07, 0x53, 0x6d, 0x73, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x18, 0x0a, 0x14, 0x53, 0x4d, 0x53, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x53, 0x4d,
	0x53, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54, 0x45, 0x52, 0x10,
	0x01, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x4d, 0x53, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4c, 0x4f,
	0x47, 0x49, 0x4e, 0x10, 0x02, 0x42, 0x0b, 0x5a, 0x09, 0x67, 0x6f, 0x2f, 0x3b, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_albelt_user_srv_const_proto_rawDescOnce sync.Once
	file_albelt_user_srv_const_proto_rawDescData = file_albelt_user_srv_const_proto_rawDesc
)

func file_albelt_user_srv_const_proto_rawDescGZIP() []byte {
	file_albelt_user_srv_const_proto_rawDescOnce.Do(func() {
		file_albelt_user_srv_const_proto_rawDescData = protoimpl.X.CompressGZIP(file_albelt_user_srv_const_proto_rawDescData)
	})
	return file_albelt_user_srv_const_proto_rawDescData
}

var file_albelt_user_srv_const_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_albelt_user_srv_const_proto_goTypes = []interface{}{
	(Gender)(0),   // 0: Gender
	(UserRole)(0), // 1: UserRole
	(SmsType)(0),  // 2: SmsType
}
var file_albelt_user_srv_const_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_albelt_user_srv_const_proto_init() }
func file_albelt_user_srv_const_proto_init() {
	if File_albelt_user_srv_const_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_albelt_user_srv_const_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_albelt_user_srv_const_proto_goTypes,
		DependencyIndexes: file_albelt_user_srv_const_proto_depIdxs,
		EnumInfos:         file_albelt_user_srv_const_proto_enumTypes,
	}.Build()
	File_albelt_user_srv_const_proto = out.File
	file_albelt_user_srv_const_proto_rawDesc = nil
	file_albelt_user_srv_const_proto_goTypes = nil
	file_albelt_user_srv_const_proto_depIdxs = nil
}
