// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.0--rc1
// source: albelt/stock_srv/svc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetStockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stock *Stock `protobuf:"bytes,1,opt,name=stock,proto3" json:"stock,omitempty"`
}

func (x *SetStockRequest) Reset() {
	*x = SetStockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_albelt_stock_srv_svc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStockRequest) ProtoMessage() {}

func (x *SetStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_albelt_stock_srv_svc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStockRequest.ProtoReflect.Descriptor instead.
func (*SetStockRequest) Descriptor() ([]byte, []int) {
	return file_albelt_stock_srv_svc_proto_rawDescGZIP(), []int{0}
}

func (x *SetStockRequest) GetStock() *Stock {
	if x != nil {
		return x.Stock
	}
	return nil
}

type SetStockResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stock *Stock `protobuf:"bytes,1,opt,name=stock,proto3" json:"stock,omitempty"`
}

func (x *SetStockResponse) Reset() {
	*x = SetStockResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_albelt_stock_srv_svc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStockResponse) ProtoMessage() {}

func (x *SetStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_albelt_stock_srv_svc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStockResponse.ProtoReflect.Descriptor instead.
func (*SetStockResponse) Descriptor() ([]byte, []int) {
	return file_albelt_stock_srv_svc_proto_rawDescGZIP(), []int{1}
}

func (x *SetStockResponse) GetStock() *Stock {
	if x != nil {
		return x.Stock
	}
	return nil
}

type GetStockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsId int32 `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
}

func (x *GetStockRequest) Reset() {
	*x = GetStockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_albelt_stock_srv_svc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockRequest) ProtoMessage() {}

func (x *GetStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_albelt_stock_srv_svc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockRequest.ProtoReflect.Descriptor instead.
func (*GetStockRequest) Descriptor() ([]byte, []int) {
	return file_albelt_stock_srv_svc_proto_rawDescGZIP(), []int{2}
}

func (x *GetStockRequest) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

type GetStockResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stock *Stock `protobuf:"bytes,1,opt,name=stock,proto3" json:"stock,omitempty"`
}

func (x *GetStockResponse) Reset() {
	*x = GetStockResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_albelt_stock_srv_svc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockResponse) ProtoMessage() {}

func (x *GetStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_albelt_stock_srv_svc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockResponse.ProtoReflect.Descriptor instead.
func (*GetStockResponse) Descriptor() ([]byte, []int) {
	return file_albelt_stock_srv_svc_proto_rawDescGZIP(), []int{3}
}

func (x *GetStockResponse) GetStock() *Stock {
	if x != nil {
		return x.Stock
	}
	return nil
}

type DecreseStocksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderSn string   `protobuf:"bytes,1,opt,name=order_sn,json=orderSn,proto3" json:"order_sn,omitempty"`
	Stocks  []*Stock `protobuf:"bytes,2,rep,name=stocks,proto3" json:"stocks,omitempty"`
}

func (x *DecreseStocksRequest) Reset() {
	*x = DecreseStocksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_albelt_stock_srv_svc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecreseStocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecreseStocksRequest) ProtoMessage() {}

func (x *DecreseStocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_albelt_stock_srv_svc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecreseStocksRequest.ProtoReflect.Descriptor instead.
func (*DecreseStocksRequest) Descriptor() ([]byte, []int) {
	return file_albelt_stock_srv_svc_proto_rawDescGZIP(), []int{4}
}

func (x *DecreseStocksRequest) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *DecreseStocksRequest) GetStocks() []*Stock {
	if x != nil {
		return x.Stocks
	}
	return nil
}

type DecreseStocksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DecreseStocksResponse) Reset() {
	*x = DecreseStocksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_albelt_stock_srv_svc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecreseStocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecreseStocksResponse) ProtoMessage() {}

func (x *DecreseStocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_albelt_stock_srv_svc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecreseStocksResponse.ProtoReflect.Descriptor instead.
func (*DecreseStocksResponse) Descriptor() ([]byte, []int) {
	return file_albelt_stock_srv_svc_proto_rawDescGZIP(), []int{5}
}

type IncreaseStocksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderSn string   `protobuf:"bytes,1,opt,name=order_sn,json=orderSn,proto3" json:"order_sn,omitempty"`
	Stocks  []*Stock `protobuf:"bytes,2,rep,name=stocks,proto3" json:"stocks,omitempty"`
}

func (x *IncreaseStocksRequest) Reset() {
	*x = IncreaseStocksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_albelt_stock_srv_svc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IncreaseStocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncreaseStocksRequest) ProtoMessage() {}

func (x *IncreaseStocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_albelt_stock_srv_svc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncreaseStocksRequest.ProtoReflect.Descriptor instead.
func (*IncreaseStocksRequest) Descriptor() ([]byte, []int) {
	return file_albelt_stock_srv_svc_proto_rawDescGZIP(), []int{6}
}

func (x *IncreaseStocksRequest) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *IncreaseStocksRequest) GetStocks() []*Stock {
	if x != nil {
		return x.Stocks
	}
	return nil
}

type IncreaseStocksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *IncreaseStocksResponse) Reset() {
	*x = IncreaseStocksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_albelt_stock_srv_svc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IncreaseStocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncreaseStocksResponse) ProtoMessage() {}

func (x *IncreaseStocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_albelt_stock_srv_svc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncreaseStocksResponse.ProtoReflect.Descriptor instead.
func (*IncreaseStocksResponse) Descriptor() ([]byte, []int) {
	return file_albelt_stock_srv_svc_proto_rawDescGZIP(), []int{7}
}

var File_albelt_stock_srv_svc_proto protoreflect.FileDescriptor

var file_albelt_stock_srv_svc_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x6c, 0x62, 0x65, 0x6c, 0x74, 0x2f, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x73,
	0x72, 0x76, 0x2f, 0x73, 0x76, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x73, 0x74,
	0x6f, 0x63, 0x6b, 0x5f, 0x73, 0x72, 0x76, 0x1a, 0x1a, 0x61, 0x6c, 0x62, 0x65, 0x6c, 0x74, 0x2f,
	0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x73, 0x72, 0x76, 0x2f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x39, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x73, 0x72,
	0x76, 0x2e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x22, 0x3a,
	0x0a, 0x10, 0x53, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x26, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x53, 0x74,
	0x6f, 0x63, 0x6b, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x22, 0x2c, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a,
	0x08, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x22, 0x3a, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53,
	0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x05,
	0x73, 0x74, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x74,
	0x6f, 0x63, 0x6b, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x05, 0x73,
	0x74, 0x6f, 0x63, 0x6b, 0x22, 0x5b, 0x0a, 0x14, 0x44, 0x65, 0x63, 0x72, 0x65, 0x73, 0x65, 0x53,
	0x74, 0x6f, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x73, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x6e, 0x12, 0x28, 0x0a, 0x06, 0x73, 0x74, 0x6f, 0x63, 0x6b,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f,
	0x73, 0x72, 0x76, 0x2e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x06, 0x73, 0x74, 0x6f, 0x63, 0x6b,
	0x73, 0x22, 0x17, 0x0a, 0x15, 0x44, 0x65, 0x63, 0x72, 0x65, 0x73, 0x65, 0x53, 0x74, 0x6f, 0x63,
	0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x5c, 0x0a, 0x15, 0x49, 0x6e,
	0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x73, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x6e, 0x12, 0x28,
	0x0a, 0x06, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x53, 0x74, 0x6f, 0x63, 0x6b,
	0x52, 0x06, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x73, 0x22, 0x18, 0x0a, 0x16, 0x49, 0x6e, 0x63, 0x72,
	0x65, 0x61, 0x73, 0x65, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x32, 0xc3, 0x02, 0x0a, 0x0c, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x43, 0x0a, 0x08, 0x53, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x12,
	0x1a, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x53, 0x65, 0x74, 0x53,
	0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x73, 0x74,
	0x6f, 0x63, 0x6b, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x53, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x53,
	0x74, 0x6f, 0x63, 0x6b, 0x12, 0x1a, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x73, 0x72, 0x76,
	0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1b, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x47, 0x65, 0x74,
	0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a,
	0x0d, 0x44, 0x65, 0x63, 0x72, 0x65, 0x73, 0x65, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x73, 0x12, 0x1f,
	0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x44, 0x65, 0x63, 0x72, 0x65,
	0x73, 0x65, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x20, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x44, 0x65, 0x63, 0x72,
	0x65, 0x73, 0x65, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x55, 0x0a, 0x0e, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x53, 0x74, 0x6f,
	0x63, 0x6b, 0x73, 0x12, 0x20, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x73, 0x72, 0x76, 0x2e,
	0x49, 0x6e, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x73, 0x72,
	0x76, 0x2e, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0b, 0x5a, 0x09, 0x67, 0x6f, 0x2f, 0x3b,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_albelt_stock_srv_svc_proto_rawDescOnce sync.Once
	file_albelt_stock_srv_svc_proto_rawDescData = file_albelt_stock_srv_svc_proto_rawDesc
)

func file_albelt_stock_srv_svc_proto_rawDescGZIP() []byte {
	file_albelt_stock_srv_svc_proto_rawDescOnce.Do(func() {
		file_albelt_stock_srv_svc_proto_rawDescData = protoimpl.X.CompressGZIP(file_albelt_stock_srv_svc_proto_rawDescData)
	})
	return file_albelt_stock_srv_svc_proto_rawDescData
}

var file_albelt_stock_srv_svc_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_albelt_stock_srv_svc_proto_goTypes = []interface{}{
	(*SetStockRequest)(nil),        // 0: stock_srv.SetStockRequest
	(*SetStockResponse)(nil),       // 1: stock_srv.SetStockResponse
	(*GetStockRequest)(nil),        // 2: stock_srv.GetStockRequest
	(*GetStockResponse)(nil),       // 3: stock_srv.GetStockResponse
	(*DecreseStocksRequest)(nil),   // 4: stock_srv.DecreseStocksRequest
	(*DecreseStocksResponse)(nil),  // 5: stock_srv.DecreseStocksResponse
	(*IncreaseStocksRequest)(nil),  // 6: stock_srv.IncreaseStocksRequest
	(*IncreaseStocksResponse)(nil), // 7: stock_srv.IncreaseStocksResponse
	(*Stock)(nil),                  // 8: stock_srv.Stock
}
var file_albelt_stock_srv_svc_proto_depIdxs = []int32{
	8, // 0: stock_srv.SetStockRequest.stock:type_name -> stock_srv.Stock
	8, // 1: stock_srv.SetStockResponse.stock:type_name -> stock_srv.Stock
	8, // 2: stock_srv.GetStockResponse.stock:type_name -> stock_srv.Stock
	8, // 3: stock_srv.DecreseStocksRequest.stocks:type_name -> stock_srv.Stock
	8, // 4: stock_srv.IncreaseStocksRequest.stocks:type_name -> stock_srv.Stock
	0, // 5: stock_srv.StockService.SetStock:input_type -> stock_srv.SetStockRequest
	2, // 6: stock_srv.StockService.GetStock:input_type -> stock_srv.GetStockRequest
	4, // 7: stock_srv.StockService.DecreseStocks:input_type -> stock_srv.DecreseStocksRequest
	6, // 8: stock_srv.StockService.IncreaseStocks:input_type -> stock_srv.IncreaseStocksRequest
	1, // 9: stock_srv.StockService.SetStock:output_type -> stock_srv.SetStockResponse
	3, // 10: stock_srv.StockService.GetStock:output_type -> stock_srv.GetStockResponse
	5, // 11: stock_srv.StockService.DecreseStocks:output_type -> stock_srv.DecreseStocksResponse
	7, // 12: stock_srv.StockService.IncreaseStocks:output_type -> stock_srv.IncreaseStocksResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_albelt_stock_srv_svc_proto_init() }
func file_albelt_stock_srv_svc_proto_init() {
	if File_albelt_stock_srv_svc_proto != nil {
		return
	}
	file_albelt_stock_srv_msg_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_albelt_stock_srv_svc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetStockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_albelt_stock_srv_svc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetStockResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_albelt_stock_srv_svc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_albelt_stock_srv_svc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStockResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_albelt_stock_srv_svc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecreseStocksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_albelt_stock_srv_svc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecreseStocksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_albelt_stock_srv_svc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IncreaseStocksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_albelt_stock_srv_svc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IncreaseStocksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_albelt_stock_srv_svc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_albelt_stock_srv_svc_proto_goTypes,
		DependencyIndexes: file_albelt_stock_srv_svc_proto_depIdxs,
		MessageInfos:      file_albelt_stock_srv_svc_proto_msgTypes,
	}.Build()
	File_albelt_stock_srv_svc_proto = out.File
	file_albelt_stock_srv_svc_proto_rawDesc = nil
	file_albelt_stock_srv_svc_proto_goTypes = nil
	file_albelt_stock_srv_svc_proto_depIdxs = nil
}
